#!/bin/sh

if xinput list-props 13 | grep "Device Enabled (184):.*1" > /dev/null
then 
    xinput disable 13
    notify-send -u low -i mouse "Touchpad Disabled" --hint=int:transient:1
else
    xinput enable 13
    notify-send -u low -i mouse "Touchpad Enabled" --hint=int:transient:1
fi
