#!/bin/bash
walls=($HOME/pictures/wallpapers/*)
if [ $(pgrep swww) ]; then
    swww img ${walls[$[ $RANDOM % ${#walls[@]} + 0 ]]} 2>/dev/null
else
    feh --bg-fill ${walls[$[ $RANDOM % ${#walls[@]} + 0 ]]} 2>/dev/null
fi
