#
# ~/.bash_profile
#

#[[ -f ~/.bashrc ]] && . ~/.bashrc
files=(~/.ASCII_Art/*)

alias ls='ls --color=auto'
alias ll='ls -lG'
alias py='python'
alias ping='ping -c 5'
alias newpf='source .bash_profile'
alias fehset='feh --bg-fill'
alias art='cat ${files[$[ $RANDOM % ${#files[@]} + 0 ]]}'
alias pfetch='~/pfetch/pkg/pfetch/usr/bin/pfetch'


if xhost >& /dev/null ; 
then 
	#echo "Display exists"
	display_exists=true
	pfetch
else 
	echo "No Display Yet" ; startx ; art ; neofetch

fi
