#
# ~/.bash_profile
#

#[[ -f ~/.bashrc ]] && . ~/.bashrc

alias ls='ls --color=auto'
alias ll='ls -lG'
alias py='python'
alias ping='ping -c 5'
alias newpf='source .bash_profile'

files=(~/.ASCII_Art/*)
cat ${files[$[ $RANDOM % ${#files[@]} + 0 ]]}
neofetch

if xhost >& /dev/null ; 
then 
	echo "Display exists"
else 
	echo "Display invalid" ; startx  

fi
