#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
files=(~/.ASCII_Art/*)

alias ls='ls --color=auto'
alias ll='ls -lG'
alias chtheme='kitty +kitten themes'
alias py='python'
alias ping='ping -c 5'
alias new='clear; source ~/.bashrc'
alias fehset='feh --bg-fill'
alias nfetch='clear; neofetch --disable gpu memory packages uptime --ascii_distro'
alias open='pcmanfm'
alias kpx='keepassxc-cli'


if [ "$TERM" == "xterm-kitty" ] || [ "$TERM" == "alacritty" ] || [ "$TERM" == "xterm-256color" ]; then
	PS1='\e[3;m\e[1;35m[🦩: \W]\$ \e[m\e[m\]'
fi

##### STARTUP HELP MESSAGE ######
if [ "$TERM" == "alacritty" ]; then
	$HOME/scripts/wallpaper
	cat ~/dwm/config.h | grep XK ; echo ""
	echo -e "       above are the system keybinds - stored in \e[1;33m$HOME/dwm/config.h\e[m"
	echo -e "       if you change these, run \e[1;33mdwmrebuild\e[m after"; echo ""
	echo -e "       a copy of the keybinds is stored in \e[1;33m$HOME/documents/keybinds\e[m"
	echo ""
fi
##### END OF STARTUP HELP MESSAGE ##### 

set -o vi

export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export SDL_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'
export RANGER_LOAD_DEFAULT_RC='FALSE'
if [ xhost >& /dev/null ] ; 
then 
	#echo "Display exists"
	display_exists=true
	pfetch
else 
	echo "No Display Yet" ; neofetch ; startx

fi
