#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# statusbar time loop
while true; do
    xsetroot -name "$(date +"%F %R")"
    sleep 1s #update every second
done &

xrandr -s <displaysize> & #set display resolution
#program autostarts
bash ~/.fehbg & #set desktop image 
alacritty &
picom -b --experimental-backends &
exec dwm
